### ISSUE TITLE
Histogram fails when using the Zyla in 11-bit mode

### ISSUE THREAD

**Issue by effting** [delmic/odemis#13] opened 2014-10-10 12:39 UTC
When using the Zyla in low noise / 11-bit read out mode, the histogram widget is displayed incorrectly

**Comment by pieleric** [comment] 2018-03-14 17:13
Closing as we haven't reproduced this bug for a long time, and the histogram code has been quite improved since then.

**Closed by pieleric** 2018-03-14 17:13 UTC
Labels: bug
